### ISSUE TITLE
大佬，请教一个疑惑

### ISSUE THREAD

**Issue by DCLangX** [cangshudada/vite-vue-tsx#1]
jsx里的事件是不是不能直接修改变量值，必须要写个方法，去修改值，我这样试了下好像不行
```
export default defineComponent({
  setup() {
    const count = ref(1);
    return {
      count,
    };
  },
  render() {
    const { count } = this;
    return (
      <button
        onClick={() => {
          count.value++;
        }}
      >
        {count}
      </button>
    );
  },
});
````

**Comment by cangshudada** [comment]
vue3 响应式变量不能使用 ES6 解构，不然会丢失响应式。你直接this.count就没问题了

**Comment by cangshudada** [comment]
> jsx里的事件是不是不能直接修改变量值，必须要写个方法，去修改值，我这样试了下好像不行
> 
> ```
> export default defineComponent({
>   setup() {
>     const count = ref(1);
>     return {
>       count,
>     };
>   },
>   render() {
>     const { count } = this;
>     return (
>       <button
>         onClick={() => {
>           count.value++;
>         }}
>       >
>         {count}
>       </button>
>     );
>   },
> });
> ```

vue3 响应式变量不能使用 ES6 解构，不然会丢失响应式。你直接this.count就没问题了

**Comment by DCLangX** [comment]
> > jsx里的事件是不是不能直接修改变量值，必须要写个方法，去修改值，我这样试了下好像不行
> > ```
> > export default defineComponent({
> >   setup() {
> >     const count = ref(1);
> >     return {
> >       count,
> >     };
> >   },
> >   render() {
> >     const { count } = this;
> >     return (
> >       <button
> >         onClick={() => {
> >           count.value++;
> >         }}
> >       >
> >         {count}
> >       </button>
> >     );
> >   },
> > });
> > ```
> 
> vue3 响应式变量不能使用 ES6 解构，不然会丢失响应式。你直接this.count就没问题了

 原来如此，我还以为只有reactive不能解构，明白了，非常感谢！😃
